---
- hosts: apache
  become: yes
  vars:
    http_port: 80
    domain: example.com
  tasks:
    - name: install apache2
      apt: name=apache2 update_cache=yes state=latest

    - name: install git
      apt: name=git update_cache=yes state=latest

    - name: enable mod-rewrite
      apache2_module: name=rewrite state=present
      notify:
        - restart apache2

    - name: apache2 listen on port {{ http_port }}
      lineinfile: dest=/etc/apache2/ports.conf regexp="^Listen " line="Listen {{ http_port }}"
      notify:
        - restart apache2

    - name: clone basic html file TO FREE /HTML/
      git: repo=https://github.com/HamBoneGS/AutoWebServerProject.git dest=/var/www/html update=no

  handlers:
    - name: restart apache2
      service: name=apache2 state=restarted
